/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 scene.gltf
Author: Zain Jafar (https://sketchfab.com/zjafar889)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mclaren-765lt-3ec7192e747a4cad9e82c1681aef6112
Title: Mclaren 765LT
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model_765LT(props) {
  const { nodes, materials } = useGLTF('/models/scene.gltf')
  const group = useRef();
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[-0.97, 0.23, -98.85]} rotation={[-Math.PI, 0, 0]} scale={-0.12}>
        <mesh geometry={nodes.Object_4.geometry} material={materials.car_paint} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.mirror} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.black_matte} />
      </group>
      <group position={[0, 0, -98.99]}>
        <group position={[0, 0.32, -0.02]}>
          <mesh geometry={nodes.Object_9.geometry} material={materials.car_paint} />
          <mesh geometry={nodes.Object_10.geometry} material={materials.black_matte} />
          <mesh geometry={nodes.Object_11.geometry} material={materials.carbon_fiber} />
        </group>
        <group position={[0, 0.32, -0.02]}>
          <mesh geometry={nodes.Object_13.geometry} material={materials.carbon_fiber} />
          <mesh geometry={nodes.Object_14.geometry} material={materials.headlight_emissive_material} />
          <mesh geometry={nodes.Object_15.geometry} material={materials.glass} />
        </group>
        <group position={[0, 0.32, -0.02]}>
          <mesh geometry={nodes.Object_17.geometry} material={materials.carbon_fiber} />
          <mesh geometry={nodes.Object_18.geometry} material={materials.black} />
        </group>
        <group position={[0, 0.32, -0.02]}>
          <mesh geometry={nodes.Object_20.geometry} material={materials.carbon_fiber} />
          <mesh geometry={nodes.Object_21.geometry} material={materials.carbon_fiber} />
        </group>
        <group position={[0, 0.32, -0.02]}>
          <mesh geometry={nodes.Object_25.geometry} material={materials.black_matte} />
          <mesh geometry={nodes.Object_26.geometry} material={materials.exhaust} />
        </group>
        <group position={[0, 0.32, -0.02]}>
          <mesh geometry={nodes.Object_30.geometry} material={materials.carbon_fiber} />
          <mesh geometry={nodes.Object_31.geometry} material={materials.black} />
          <mesh geometry={nodes.Object_32.geometry} material={materials.black_matte} />
        </group>
        <group position={[0, 0.32, -0.02]}>
          <mesh geometry={nodes.Object_34.geometry} material={materials.carbon_fiber} />
          <mesh geometry={nodes.Object_35.geometry} material={materials.black} />
        </group>
        <group position={[0, 0.32, -0.02]}>
          <mesh geometry={nodes.Object_40.geometry} material={materials.carbon_fiber} />
          <mesh geometry={nodes.Object_41.geometry} material={materials.glass} />
          <mesh geometry={nodes.Object_42.geometry} material={materials.headlight_emissive_material} />
          <mesh geometry={nodes.Object_43.geometry} material={materials.black_matte} />
          <mesh geometry={nodes.Object_44.geometry} material={materials.headlights} />
          <mesh geometry={nodes.Object_45.geometry} material={materials.headlight_grille} />
        </group>
        <group position={[0, 0, 0.38]}>
          <mesh geometry={nodes.Object_47.geometry} material={materials.seats} />
          <mesh geometry={nodes.Object_48.geometry} material={materials.interior} />
          <mesh geometry={nodes.Object_49.geometry} material={materials.black_matte} />
          <mesh geometry={nodes.Object_50.geometry} material={materials.metal} />
          <mesh geometry={nodes.Object_51.geometry} material={materials.tablet} />
          <mesh geometry={nodes.Object_52.geometry} material={materials.logo} />
          <mesh geometry={nodes.Object_53.geometry} material={materials.logo_outline} />
          <mesh geometry={nodes.Object_54.geometry} material={materials.carbon_fiber} />
        </group>
        <group position={[0, 0.32, -0.02]}>
          <mesh geometry={nodes.Object_58.geometry} material={materials.carbon_fiber} />
          <mesh geometry={nodes.Object_59.geometry} material={materials.taillight_glass} />
          <mesh geometry={nodes.Object_60.geometry} material={materials.taillight_emissive_material} />
        </group>
        <group position={[0, 0.32, -0.02]}>
          <mesh geometry={nodes.Object_64.geometry} material={materials.glass_black} />
          <mesh geometry={nodes.Object_65.geometry} material={materials.black_matte} />
          <mesh geometry={nodes.Object_66.geometry} material={materials.glass} />
        </group>
        <group position={[0, 0.32, -0.02]}>
          <mesh geometry={nodes.Object_68.geometry} material={materials.carbon_fiber} />
          <mesh geometry={nodes.Object_69.geometry} material={materials.grille} />
        </group>
        <group position={[0, 0.32, -0.02]}>
          <mesh geometry={nodes.Object_77.geometry} material={materials.black_matte} />
          <mesh geometry={nodes.Object_78.geometry} material={materials.taillight_emissive_material} />
        </group>
        <group position={[0, 0.32, -0.02]}>
          <mesh geometry={nodes.Object_82.geometry} material={materials.glass} />
          <mesh geometry={nodes.Object_83.geometry} material={materials.black_matte} />
          <mesh geometry={nodes.Object_84.geometry} material={materials.interior} />
          <mesh geometry={nodes.Object_85.geometry} material={materials.glass_black} />
        </group>
        <group position={[0, 0.32, -0.02]}>
          <mesh geometry={nodes.Object_87.geometry} material={materials.glass_black} />
          <mesh geometry={nodes.Object_88.geometry} material={materials.glass} />
          <mesh geometry={nodes.Object_89.geometry} material={materials.black_matte} />
        </group>
        <mesh geometry={nodes.Object_23.geometry} material={materials.engine} position={[0, 0.32, -0.02]} />
        <mesh geometry={nodes.Object_28.geometry} material={materials.black_matte} position={[0, 0.32, -0.02]} />
        <mesh geometry={nodes.Object_37.geometry} material={materials.black_matte} />
        <mesh geometry={nodes.Object_38.geometry} material={materials.black} />
        <mesh geometry={nodes.Object_56.geometry} material={materials.carbon_fiber} position={[0.01, 0.32, -0.02]} />
        <mesh geometry={nodes.Object_62.geometry} material={materials.black_matte} position={[0, 0.32, -0.1]} scale={1.01} />
        <mesh geometry={nodes.Object_71.geometry} material={materials.car_paint} position={[0, 0.32, 0]} />
        <mesh geometry={nodes.Object_73.geometry} material={materials.carbon_fiber} position={[0, 0.32, 0]} />
        <mesh geometry={nodes.Object_75.geometry} material={materials.car_paint} position={[0, 0.32, 0]} />
        <mesh geometry={nodes.Object_80.geometry} material={materials.taillight_glass} position={[0, 0.32, -0.02]} />
      </group>
      <group position={[0.64, 0.22, -98.71]} rotation={[0.06, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.33}>
          <mesh geometry={nodes.Object_92.geometry} material={materials.brake_disc} />
          <mesh geometry={nodes.Object_93.geometry} material={materials.brake_disc_holes} />
        </group>
        <group rotation={[-0.32, 0, 0]}>
          <mesh geometry={nodes.Object_95.geometry} material={materials.rims} />
          <mesh geometry={nodes.Object_96.geometry} material={materials.rims} />
          <mesh geometry={nodes.Object_97.geometry} material={materials.rims} />
          <mesh geometry={nodes.Object_98.geometry} material={materials.rims} />
          <mesh geometry={nodes.Object_99.geometry} material={materials.rims} />
          <mesh geometry={nodes.Object_100.geometry} material={materials.rims} />
          <mesh geometry={nodes.Object_101.geometry} material={materials.logo} />
          <mesh geometry={nodes.Object_102.geometry} material={materials.logo_outline} />
        </group>
      </group>
      <group position={[0.64, 0.22, -100.49]} rotation={[0.06, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.33}>
          <mesh geometry={nodes.Object_105.geometry} material={materials.brake_disc} />
          <mesh geometry={nodes.Object_106.geometry} material={materials.brake_disc_holes} />
        </group>
        <group rotation={[-0.32, 0, 0]}>
          <mesh geometry={nodes.Object_108.geometry} material={materials.rims} />
          <mesh geometry={nodes.Object_109.geometry} material={materials.rims} />
          <mesh geometry={nodes.Object_110.geometry} material={materials.rims} />
          <mesh geometry={nodes.Object_111.geometry} material={materials.rims} />
          <mesh geometry={nodes.Object_112.geometry} material={materials.rims} />
          <mesh geometry={nodes.Object_113.geometry} material={materials.rims} />
          <mesh geometry={nodes.Object_114.geometry} material={materials.logo} />
          <mesh geometry={nodes.Object_115.geometry} material={materials.logo_outline} />
        </group>
      </group>
      <group position={[0.48, 0.21, -98.71]} rotation={[-Math.PI, 0, 0]} scale={[-0.11, -0.14, -0.11]}>
        <mesh geometry={nodes.Object_117.geometry} material={materials.tyre} />
        <mesh geometry={nodes.Object_118.geometry} material={materials.tyre} />
      </group>
      <group position={[0.49, 0.21, -100.49]} rotation={[-Math.PI, 0, 0]} scale={[-0.11, -0.14, -0.11]}>
        <mesh geometry={nodes.Object_120.geometry} material={materials.tyre} />
        <mesh geometry={nodes.Object_121.geometry} material={materials.tyre} />
      </group>
      <group position={[0.64, 0.22, -98.71]} rotation={[-0.74, 0, 0]} scale={0.21}>
        <mesh geometry={nodes.Object_123.geometry} material={materials.calipers} />
        <mesh geometry={nodes.Object_124.geometry} material={materials.material_0} />
      </group>
      <group position={[0.64, 0.22, -100.49]} rotation={[-0.74, 0, 0]} scale={0.21}>
        <mesh geometry={nodes.Object_126.geometry} material={materials.calipers} />
        <mesh geometry={nodes.Object_127.geometry} material={materials.material_0} />
      </group>
    </group>
  )
}

